(cl:defpackage img_manip-msg
  (:use )
  (:export
   "<PIXELCOUNTACTION>"
   "PIXELCOUNTACTION"
   "<PIXELCOUNTACTIONRESULT>"
   "PIXELCOUNTACTIONRESULT"
   "<PIXELCOUNTGOAL>"
   "PIXELCOUNTGOAL"
   "<PIXELCOUNTACTIONFEEDBACK>"
   "PIXELCOUNTACTIONFEEDBACK"
   "<PIXELCOUNTRESULT>"
   "PIXELCOUNTRESULT"
   "<PIXELCOUNTFEEDBACK>"
   "PIXELCOUNTFEEDBACK"
   "<PIXELCOUNTACTIONGOAL>"
   "PIXELCOUNTACTIONGOAL"
  ))

