; Auto-generated. Do not edit!


(cl:in-package img_manip-msg)


;//! \htmlinclude pixelCountFeedback.msg.html

(cl:defclass <pixelCountFeedback> (roslisp-msg-protocol:ros-message)
  ((n_progress
    :reader n_progress
    :initarg :n_progress
    :type cl:integer
    :initform 0))
)

(cl:defclass pixelCountFeedback (<pixelCountFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pixelCountFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pixelCountFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name img_manip-msg:<pixelCountFeedback> is deprecated: use img_manip-msg:pixelCountFeedback instead.")))

(cl:ensure-generic-function 'n_progress-val :lambda-list '(m))
(cl:defmethod n_progress-val ((m <pixelCountFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader img_manip-msg:n_progress-val is deprecated.  Use img_manip-msg:n_progress instead.")
  (n_progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pixelCountFeedback>) ostream)
  "Serializes a message object of type '<pixelCountFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'n_progress)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'n_progress)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'n_progress)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'n_progress)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pixelCountFeedback>) istream)
  "Deserializes a message object of type '<pixelCountFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'n_progress)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'n_progress)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'n_progress)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'n_progress)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pixelCountFeedback>)))
  "Returns string type for a message object of type '<pixelCountFeedback>"
  "img_manip/pixelCountFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pixelCountFeedback)))
  "Returns string type for a message object of type 'pixelCountFeedback"
  "img_manip/pixelCountFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pixelCountFeedback>)))
  "Returns md5sum for a message object of type '<pixelCountFeedback>"
  "f07532da405150f41648b64daa1bcb4c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pixelCountFeedback)))
  "Returns md5sum for a message object of type 'pixelCountFeedback"
  "f07532da405150f41648b64daa1bcb4c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pixelCountFeedback>)))
  "Returns full string definition for message of type '<pixelCountFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback message~%uint32 n_progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pixelCountFeedback)))
  "Returns full string definition for message of type 'pixelCountFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback message~%uint32 n_progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pixelCountFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pixelCountFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'pixelCountFeedback
    (cl:cons ':n_progress (n_progress msg))
))
