; Auto-generated. Do not edit!


(cl:in-package img_manip-msg)


;//! \htmlinclude pixelCountResult.msg.html

(cl:defclass <pixelCountResult> (roslisp-msg-protocol:ros-message)
  ((nPixels
    :reader nPixels
    :initarg :nPixels
    :type cl:integer
    :initform 0))
)

(cl:defclass pixelCountResult (<pixelCountResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pixelCountResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pixelCountResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name img_manip-msg:<pixelCountResult> is deprecated: use img_manip-msg:pixelCountResult instead.")))

(cl:ensure-generic-function 'nPixels-val :lambda-list '(m))
(cl:defmethod nPixels-val ((m <pixelCountResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader img_manip-msg:nPixels-val is deprecated.  Use img_manip-msg:nPixels instead.")
  (nPixels m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pixelCountResult>) ostream)
  "Serializes a message object of type '<pixelCountResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nPixels)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nPixels)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nPixels)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nPixels)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pixelCountResult>) istream)
  "Deserializes a message object of type '<pixelCountResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nPixels)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nPixels)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nPixels)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nPixels)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pixelCountResult>)))
  "Returns string type for a message object of type '<pixelCountResult>"
  "img_manip/pixelCountResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pixelCountResult)))
  "Returns string type for a message object of type 'pixelCountResult"
  "img_manip/pixelCountResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pixelCountResult>)))
  "Returns md5sum for a message object of type '<pixelCountResult>"
  "8eeb56c1d30c8875e455f5e30c88fa1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pixelCountResult)))
  "Returns md5sum for a message object of type 'pixelCountResult"
  "8eeb56c1d30c8875e455f5e30c88fa1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pixelCountResult>)))
  "Returns full string definition for message of type '<pixelCountResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%uint32 nPixels~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pixelCountResult)))
  "Returns full string definition for message of type 'pixelCountResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%uint32 nPixels~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pixelCountResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pixelCountResult>))
  "Converts a ROS message object to a list"
  (cl:list 'pixelCountResult
    (cl:cons ':nPixels (nPixels msg))
))
