// Generated by gencpp from file img_manip/pixelCountResult.msg
// DO NOT EDIT!


#ifndef IMG_MANIP_MESSAGE_PIXELCOUNTRESULT_H
#define IMG_MANIP_MESSAGE_PIXELCOUNTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace img_manip
{
template <class ContainerAllocator>
struct pixelCountResult_
{
  typedef pixelCountResult_<ContainerAllocator> Type;

  pixelCountResult_()
    : nPixels(0)  {
    }
  pixelCountResult_(const ContainerAllocator& _alloc)
    : nPixels(0)  {
    }



   typedef uint32_t _nPixels_type;
  _nPixels_type nPixels;




  typedef boost::shared_ptr< ::img_manip::pixelCountResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::img_manip::pixelCountResult_<ContainerAllocator> const> ConstPtr;

}; // struct pixelCountResult_

typedef ::img_manip::pixelCountResult_<std::allocator<void> > pixelCountResult;

typedef boost::shared_ptr< ::img_manip::pixelCountResult > pixelCountResultPtr;
typedef boost::shared_ptr< ::img_manip::pixelCountResult const> pixelCountResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::img_manip::pixelCountResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::img_manip::pixelCountResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace img_manip

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'img_manip': ['/home/student/catkin_ws/devel/share/img_manip/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::img_manip::pixelCountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::img_manip::pixelCountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::img_manip::pixelCountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::img_manip::pixelCountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_manip::pixelCountResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_manip::pixelCountResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::img_manip::pixelCountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8eeb56c1d30c8875e455f5e30c88fa1f";
  }

  static const char* value(const ::img_manip::pixelCountResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8eeb56c1d30c8875ULL;
  static const uint64_t static_value2 = 0xe455f5e30c88fa1fULL;
};

template<class ContainerAllocator>
struct DataType< ::img_manip::pixelCountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "img_manip/pixelCountResult";
  }

  static const char* value(const ::img_manip::pixelCountResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::img_manip::pixelCountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
uint32 nPixels\n\
";
  }

  static const char* value(const ::img_manip::pixelCountResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::img_manip::pixelCountResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nPixels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pixelCountResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::img_manip::pixelCountResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::img_manip::pixelCountResult_<ContainerAllocator>& v)
  {
    s << indent << "nPixels: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nPixels);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMG_MANIP_MESSAGE_PIXELCOUNTRESULT_H
