(cl:defpackage img_manip-srv
  (:use )
  (:export
   "RGB2GRAY (COPY)"
   "<RGB2GRAY (COPY)-REQUEST>"
   "RGB2GRAY (COPY)-REQUEST"
   "<RGB2GRAY (COPY)-RESPONSE>"
   "RGB2GRAY (COPY)-RESPONSE"
   "RGB2GRAY"
   "<RGB2GRAY-REQUEST>"
   "RGB2GRAY-REQUEST"
   "<RGB2GRAY-RESPONSE>"
   "RGB2GRAY-RESPONSE"
  ))

